### ISSUE TITLE
HardwareIdentification.GetPackageSpecificToken(null)

### ISSUE THREAD

**Issue by yxylpj** [ljw1004/uwp-desktop#4]
Hello
I had review the project, but i can not know how it works.
I run the DemoCS project, some error with it.

I want to get hardware information with HardwareIdentification.GetPackageSpecificToken(null) in winform project.

Thanks a lot.

**Comment by ljw1004** [comment]
This api "get PACKAGE specific token" returns a token that's specific to the particular .appx package that you're part of. (I think they do it this way as part of the sandbox, to prevent one app from obtaining the hardware ID, and then having a second completely unrelated app obtain the same ID and correlate between the two apps).

A regular winforms application is never part of an appx package. Therefore the call will fail.

However Microsoft have been working on something called "Project Centennial", now called "Desktop App Converter". It lets you take your existing winforms/WPF apps and bundle them up into .appx so they can be downloaded+installed from the store (or "sideloaded" and installed locally without the store). It's possible that `HardwareIdentification.GetPackageSpecificToken` will be supported by such a Winforms project; I don't know for sure.

You should try it! Get started with the Desktop App Converter here:
https://developer.microsoft.com/en-us/windows/bridges/desktop
